const TCT_CUSTOM_LANGUAGE = "__custom__";

const TCT_SOURCE_LANGUAGES = [
  ["English (US)", "English (US)"],
  ["English (Canada)", "English (Canada)"],
  ["English (India)", "English (India)"],
  ["English (UK)", "English (UK)"],
  ["English (Australia)", "English (Australia)"],
  ["English (New Zealand)", "English (New Zealand)"],
  ["Arabic (Saudi Arabia)", "Arabic (Saudi Arabia)"],
  ["Arabic (United Arab Emirates)", "Arabic (United Arab Emirates)"],
  ["Albanian (Albania)", "Albanian (Albania)"],
  ["Bulgarian (Bulgaria)", "Bulgarian (Bulgaria)"],
  ["Catalan (Catalan)", "Catalan (Catalan)"],
  ["Chinese (Simplified, China)", "Chinese (Simplified, China)"],
  ["Chinese (Traditional, Hong Kong SAR)", "Chinese (Traditional, Hong Kong SAR)"],
  ["Chinese (Traditional, Taiwan)", "Chinese (Traditional, Taiwan)"],
  ["Croatian (Croatia)", "Croatian (Croatia)"],
  ["Czech (Czechia)", "Czech (Czechia)"],
  ["Danish (Denmark)", "Danish (Denmark)"],
  ["Dutch (Belgium)", "Dutch (Belgium)"],
  ["Dutch (Netherlands)", "Dutch (Netherlands)"],
  ["Estonian (Estonia)", "Estonian (Estonia)"],
  ["Filipino (Philippines)", "Filipino (Philippines)"],
  ["Finnish (Finland)", "Finnish (Finland)"],
  ["French (Canada)", "French (Canada)"],
  ["French (France)", "French (France)"],
  ["German (Germany)", "German (Germany)"],
  ["German (Switzerland)", "German (Switzerland)"],
  ["Greek (Greece)", "Greek (Greece)"],
  ["Hebrew (Israel)", "Hebrew (Israel)"],
  ["Hindi (India)", "Hindi (India)"],
  ["Hungarian (Hungary)", "Hungarian (Hungary)"],
  ["Icelandic (Iceland)", "Icelandic (Iceland)"],
  ["Indonesian (Indonesia)", "Indonesian (Indonesia)"],
  ["Italian (Italy)", "Italian (Italy)"],
  ["Japanese (Japan)", "Japanese (Japan)"],
  ["Kazakh (Kazakhstan)", "Kazakh (Kazakhstan)"],
  ["Korean (Korea)", "Korean (Korea)"],
  ["Latvian (Latvia)", "Latvian (Latvia)"],
  ["Lithuanian (Lithuania)", "Lithuanian (Lithuania)"],
  ["Malay (Malaysia)", "Malay (Malaysia)"],
  ["Maltese (Malta)", "Maltese (Malta)"],
  ["Norwegian (Norway)", "Norwegian (Norway)"],
  ["Polish (Poland)", "Polish (Poland)"],
  ["Portuguese (Brazil)", "Portuguese (Brazil)"],
  ["Portuguese (Portugal)", "Portuguese (Portugal)"],
  ["Romanian (Romania)", "Romanian (Romania)"],
  ["Russian (Russia)", "Russian (Russia)"],
  ["Serbian (Cyrillic, Serbia)", "Serbian (Cyrillic, Serbia)"],
  ["Slovak (Slovakia)", "Slovak (Slovakia)"],
  ["Slovenian (Slovenia)", "Slovenian (Slovenia)"],
  ["Spanish (Mexico)", "Spanish (Mexico)"],
  ["Spanish (Spain)", "Spanish (Spain)"],
  ["Swedish (Sweden)", "Swedish (Sweden)"],
  ["Thai (Thailand)", "Thai (Thailand)"],
  ["Turkish (Turkey)", "Turkish (Turkey)"],
  ["Ukrainian (Ukraine)", "Ukrainian (Ukraine)"],
  ["Vietnamese (Vietnam)", "Vietnamese (Vietnam)"],
  ["Welsh (United Kingdom)", "Welsh (United Kingdom)"]
];

const TCT_TARGET_LANGUAGES = [
  ["Arabic", "Arabic"],
  ["Chinese Simplified", "Chinese Simplified"],
  ["Chinese Traditional", "Chinese Traditional"],
  ["Czech", "Czech"],
  ["Danish", "Danish"],
  ["Dutch", "Dutch"],
  ["English", "English"],
  ["Finnish", "Finnish"],
  ["French", "French"],
  ["French (Canada)", "French (Canada)"],
  ["German", "German"],
  ["Greek", "Greek"],
  ["Hebrew", "Hebrew"],
  ["Hindi", "Hindi"],
  ["Hungarian", "Hungarian"],
  ["Italian", "Italian"],
  ["Japanese", "Japanese"],
  ["Korean", "Korean"],
  ["Norwegian", "Norwegian"],
  ["Polish", "Polish"],
  ["Portuguese (Brazil)", "Portuguese (Brazil)"],
  ["Portuguese (Portugal)", "Portuguese (Portugal)"],
  ["Romanian", "Romanian"],
  ["Russian", "Russian"],
  ["Slovak", "Slovak"],
  ["Spanish", "Spanish"],
  ["Swedish", "Swedish"],
  ["Thai", "Thai"],
  ["Turkish", "Turkish"],
  ["Ukrainian", "Ukrainian"],
  ["Vietnamese", "Vietnamese"]
];
