const TCT_CUSTOM_LANGUAGE = "__custom__";

const TCT_SOURCE_LANGUAGES = [
  ["English (US)", "English (US)"],
  ["English (Canada)", "English (Canada)"],
  ["English (India)", "English (India)"],
  ["English (UK)", "English (UK)"],
  ["English (Australia)", "English (Australia)"],
  ["English (New Zealand)", "English (New Zealand)"],
  ["Arabic (Saudi Arabia)", "العربية (المملكة العربية السعودية)"],
  ["Arabic (United Arab Emirates)", "العربية (الإمارات العربية المتحدة)"],
  ["Albanian (Albania)", "Shqip (Shqipëria)"],
  ["Bulgarian (Bulgaria)", "Български (България)"],
  ["Catalan (Catalan)", "Català"],
  ["Chinese (Simplified, China)", "中文（简体，中国）"],
  ["Chinese (Traditional, Hong Kong SAR)", "中文（繁體，香港特別行政區）"],
  ["Chinese (Traditional, Taiwan)", "中文（繁體，台灣）"],
  ["Croatian (Croatia)", "Hrvatski (Hrvatska)"],
  ["Czech (Czechia)", "Čeština (Česko)"],
  ["Danish (Denmark)", "Dansk (Danmark)"],
  ["Dutch (Belgium)", "Nederlands (België)"],
  ["Dutch (Netherlands)", "Nederlands (Nederland)"],
  ["Estonian (Estonia)", "Eesti (Eesti)"],
  ["Filipino (Philippines)", "Filipino (Pilipinas)"],
  ["Finnish (Finland)", "Suomi (Suomi)"],
  ["French (Canada)", "Français (Canada)"],
  ["French (France)", "Français (France)"],
  ["German (Germany)", "Deutsch (Deutschland)"],
  ["German (Switzerland)", "Deutsch (Schweiz)"],
  ["Greek (Greece)", "Ελληνικά (Ελλάδα)"],
  ["Hebrew (Israel)", "עברית (ישראל)"],
  ["Hindi (India)", "हिन्दी (भारत)"],
  ["Hungarian (Hungary)", "Magyar (Magyarország)"],
  ["Icelandic (Iceland)", "Íslenska (Ísland)"],
  ["Indonesian (Indonesia)", "Bahasa Indonesia (Indonesia)"],
  ["Italian (Italy)", "Italiano (Italia)"],
  ["Japanese (Japan)", "日本語（日本）"],
  ["Kazakh (Kazakhstan)", "Қазақша (Қазақстан)"],
  ["Korean (Korea)", "한국어 (대한민국)"],
  ["Latvian (Latvia)", "Latviešu (Latvija)"],
  ["Lithuanian (Lithuania)", "Lietuvių (Lietuva)"],
  ["Malay (Malaysia)", "Bahasa Melayu (Malaysia)"],
  ["Maltese (Malta)", "Malti (Malta)"],
  ["Norwegian (Norway)", "Norsk (Norge)"],
  ["Polish (Poland)", "Polski (Polska)"],
  ["Portuguese (Brazil)", "Português (Brasil)"],
  ["Portuguese (Portugal)", "Português (Portugal)"],
  ["Romanian (Romania)", "Română (România)"],
  ["Russian (Russia)", "Русский (Россия)"],
  ["Serbian (Cyrillic, Serbia)", "Српски (Србија)"],
  ["Slovak (Slovakia)", "Slovenčina (Slovensko)"],
  ["Slovenian (Slovenia)", "Slovenščina (Slovenija)"],
  ["Spanish (Mexico)", "Español (México)"],
  ["Spanish (Spain)", "Español (España)"],
  ["Swedish (Sweden)", "Svenska (Sverige)"],
  ["Thai (Thailand)", "ไทย (ประเทศไทย)"],
  ["Turkish (Turkey)", "Türkçe (Türkiye)"],
  ["Ukrainian (Ukraine)", "Українська (Україна)"],
  ["Vietnamese (Vietnam)", "Tiếng Việt (Việt Nam)"],
  ["Welsh (United Kingdom)", "Cymraeg (Y Deyrnas Unedig)"]
];

const TCT_TARGET_LANGUAGES = [
  ["Arabic", "العربية — Arabic"],
  ["Chinese Simplified", "中文（简体）— Chinese Simplified"],
  ["Chinese Traditional", "中文（繁體）— Chinese Traditional"],
  ["Czech", "Čeština — Czech"],
  ["Danish", "Dansk — Danish"],
  ["Dutch", "Nederlands — Dutch"],
  ["English", "English"],
  ["Finnish", "Suomi — Finnish"],
  ["French", "Français — French"],
  ["French (Canada)", "Français (Canada) — French (Canada)"],
  ["German", "Deutsch — German"],
  ["Greek", "Ελληνικά — Greek"],
  ["Hebrew", "עברית — Hebrew"],
  ["Hindi", "हिन्दी — Hindi"],
  ["Hungarian", "Magyar — Hungarian"],
  ["Italian", "Italiano — Italian"],
  ["Japanese", "日本語 — Japanese"],
  ["Korean", "한국어 — Korean"],
  ["Norwegian", "Norsk — Norwegian"],
  ["Polish", "Polski — Polish"],
  ["Portuguese (Brazil)", "Português (Brasil) — Portuguese (Brazil)"],
  ["Portuguese (Portugal)", "Português (Portugal) — Portuguese (Portugal)"],
  ["Romanian", "Română — Romanian"],
  ["Russian", "Русский — Russian"],
  ["Slovak", "Slovenčina — Slovak"],
  ["Spanish", "Español — Spanish"],
  ["Swedish", "Svenska — Swedish"],
  ["Thai", "ไทย — Thai"],
  ["Turkish", "Türkçe — Turkish"],
  ["Ukrainian", "Українська — Ukrainian"],
  ["Vietnamese", "Tiếng Việt — Vietnamese"]
];
